### ISSUE TITLE
Don't commit unnecessary stuff

### ISSUE THREAD

**Issue by TBotV63** [meguy26/RemoteConsole#1]
Don't commit the project gradle home (/.gradle)
Don't commit eclipse project / classpath files.

See .gitignore

Also, it's kinda a mess the way you have a RemoteConsole and a RemoteConsole1 inside a RemoteConsole folder :grinning:

As a rule of thumb, initialize the git repo where your project files are (the build.gradle, the .project, etc...)

**Comment by meguy26** [comment]
See I thought that I was doing it right, but I think I accidentally committed two projects, it wont happen again. (Probably).
